steps:
  - name: 'gcr.io/sjm-test/docker'
    args: [ 'build', '-t', 'gcr.io/sjm-test/fifi:latest', '.' , '-f', 'Dockerfile']
  # push the container image to Container Registry
  - name: 'gcr.io/sjm-test/docker'
    args: ['push', 'gcr.io/sjm-test/fifi:latest']
  - name: "gcr.io/sjm-test/gke-deploy"
    args:
    - run
    - --filename=pods.yaml
    - --image=gcr.io/sjm-test/fifi:latest
    - --location=us-central1-c
    - --cluster=cluster-1
  - name: 'gcr.io/sjm-test/kubectl'
    args: ['apply', '-f', 'lb.yaml']
    env:
     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
     - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
options:
   logging: CLOUD_LOGGING_ONLY
