steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/sjm-test/fifi', '.' , '-f', 'Dockerfile']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sjm-test/fifi']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=onlyyamls/deployment.yaml
    - --image=gcr.io/sjm-test/fifi
    - --location=us-central1-c
    - --cluster=cluster-1
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'onlyyamls/lb.yaml']
    env:
     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
     - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
options:
   logging: CLOUD_LOGGING_ONLY
